Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "ginger")
Ingredient.create(name: "coke")
Ingredient.create(name: "lime")
Ingredient.create(name: "tonic water")
